### ISSUE TITLE
Location of Log-File?

### ISSUE THREAD

**Issue by PolynomialDivision** [lsinfo3/yomo-wrapperapp#1]
I'm using the app on my Smartphone (Xiaomi Redmi Note 3)
I can open the statistics section in the app, but there is the log file located on the phone?

**Comment by iamtorchstack** [comment]
@PolynomialDivision Did you clone and run the app on your phone?

**Comment by iamtorchstack** [comment]
Hi Polynomial How can you help me with a guide on running this application on my phone please
